/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppFetcher {}
  interface AppFetcherAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppSpinner {}
  interface AppSpinnerAttributes extends StencilHTMLAttributes {}

  interface AppStorylist {
    'data': Object[];
    'hasError': boolean;
    'isListEnd': boolean;
    'isLoading': boolean;
    'ref': (el?: HTMLDivElement) => void;
  }
  interface AppStorylistAttributes extends StencilHTMLAttributes {
    'data'?: Object[];
    'hasError'?: boolean;
    'isListEnd'?: boolean;
    'isLoading'?: boolean;
    'ref'?: (el?: HTMLDivElement) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppFetcher': Components.AppFetcher;
    'AppRoot': Components.AppRoot;
    'AppSpinner': Components.AppSpinner;
    'AppStorylist': Components.AppStorylist;
  }

  interface StencilIntrinsicElements {
    'app-fetcher': Components.AppFetcherAttributes;
    'app-root': Components.AppRootAttributes;
    'app-spinner': Components.AppSpinnerAttributes;
    'app-storylist': Components.AppStorylistAttributes;
  }


  interface HTMLAppFetcherElement extends Components.AppFetcher, HTMLStencilElement {}
  var HTMLAppFetcherElement: {
    prototype: HTMLAppFetcherElement;
    new (): HTMLAppFetcherElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSpinnerElement extends Components.AppSpinner, HTMLStencilElement {}
  var HTMLAppSpinnerElement: {
    prototype: HTMLAppSpinnerElement;
    new (): HTMLAppSpinnerElement;
  };

  interface HTMLAppStorylistElement extends Components.AppStorylist, HTMLStencilElement {}
  var HTMLAppStorylistElement: {
    prototype: HTMLAppStorylistElement;
    new (): HTMLAppStorylistElement;
  };

  interface HTMLElementTagNameMap {
    'app-fetcher': HTMLAppFetcherElement
    'app-root': HTMLAppRootElement
    'app-spinner': HTMLAppSpinnerElement
    'app-storylist': HTMLAppStorylistElement
  }

  interface ElementTagNameMap {
    'app-fetcher': HTMLAppFetcherElement;
    'app-root': HTMLAppRootElement;
    'app-spinner': HTMLAppSpinnerElement;
    'app-storylist': HTMLAppStorylistElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
