/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppSpinner {}
  interface AppSpinnerAttributes extends StencilHTMLAttributes {}

  interface AppStories {}
  interface AppStoriesAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'AppSpinner': Components.AppSpinner;
    'AppStories': Components.AppStories;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'app-spinner': Components.AppSpinnerAttributes;
    'app-stories': Components.AppStoriesAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppSpinnerElement extends Components.AppSpinner, HTMLStencilElement {}
  var HTMLAppSpinnerElement: {
    prototype: HTMLAppSpinnerElement;
    new (): HTMLAppSpinnerElement;
  };

  interface HTMLAppStoriesElement extends Components.AppStories, HTMLStencilElement {}
  var HTMLAppStoriesElement: {
    prototype: HTMLAppStoriesElement;
    new (): HTMLAppStoriesElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'app-spinner': HTMLAppSpinnerElement
    'app-stories': HTMLAppStoriesElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'app-spinner': HTMLAppSpinnerElement;
    'app-stories': HTMLAppStoriesElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
